// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: internal/anylistpb/anylist.proto

package anylistpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShoppingList_ListItemSortOrder int32

const (
	ShoppingList_Manual       ShoppingList_ListItemSortOrder = 0
	ShoppingList_Alphabetical ShoppingList_ListItemSortOrder = 1
)

// Enum value maps for ShoppingList_ListItemSortOrder.
var (
	ShoppingList_ListItemSortOrder_name = map[int32]string{
		0: "Manual",
		1: "Alphabetical",
	}
	ShoppingList_ListItemSortOrder_value = map[string]int32{
		"Manual":       0,
		"Alphabetical": 1,
	}
)

func (x ShoppingList_ListItemSortOrder) Enum() *ShoppingList_ListItemSortOrder {
	p := new(ShoppingList_ListItemSortOrder)
	*p = x
	return p
}

func (x ShoppingList_ListItemSortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShoppingList_ListItemSortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_anylistpb_anylist_proto_enumTypes[0].Descriptor()
}

func (ShoppingList_ListItemSortOrder) Type() protoreflect.EnumType {
	return &file_internal_anylistpb_anylist_proto_enumTypes[0]
}

func (x ShoppingList_ListItemSortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ShoppingList_ListItemSortOrder) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ShoppingList_ListItemSortOrder(num)
	return nil
}

// Deprecated: Use ShoppingList_ListItemSortOrder.Descriptor instead.
func (ShoppingList_ListItemSortOrder) EnumDescriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{0, 0}
}

type ShoppingList_NewListItemPosition int32

const (
	ShoppingList_Bottom ShoppingList_NewListItemPosition = 0
	ShoppingList_Top    ShoppingList_NewListItemPosition = 1
)

// Enum value maps for ShoppingList_NewListItemPosition.
var (
	ShoppingList_NewListItemPosition_name = map[int32]string{
		0: "Bottom",
		1: "Top",
	}
	ShoppingList_NewListItemPosition_value = map[string]int32{
		"Bottom": 0,
		"Top":    1,
	}
)

func (x ShoppingList_NewListItemPosition) Enum() *ShoppingList_NewListItemPosition {
	p := new(ShoppingList_NewListItemPosition)
	*p = x
	return p
}

func (x ShoppingList_NewListItemPosition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShoppingList_NewListItemPosition) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_anylistpb_anylist_proto_enumTypes[1].Descriptor()
}

func (ShoppingList_NewListItemPosition) Type() protoreflect.EnumType {
	return &file_internal_anylistpb_anylist_proto_enumTypes[1]
}

func (x ShoppingList_NewListItemPosition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ShoppingList_NewListItemPosition) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ShoppingList_NewListItemPosition(num)
	return nil
}

// Deprecated: Use ShoppingList_NewListItemPosition.Descriptor instead.
func (ShoppingList_NewListItemPosition) EnumDescriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{0, 1}
}

type PBListFolderItem_ItemType int32

const (
	PBListFolderItem_ListType   PBListFolderItem_ItemType = 0
	PBListFolderItem_FolderType PBListFolderItem_ItemType = 1
)

// Enum value maps for PBListFolderItem_ItemType.
var (
	PBListFolderItem_ItemType_name = map[int32]string{
		0: "ListType",
		1: "FolderType",
	}
	PBListFolderItem_ItemType_value = map[string]int32{
		"ListType":   0,
		"FolderType": 1,
	}
)

func (x PBListFolderItem_ItemType) Enum() *PBListFolderItem_ItemType {
	p := new(PBListFolderItem_ItemType)
	*p = x
	return p
}

func (x PBListFolderItem_ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PBListFolderItem_ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_anylistpb_anylist_proto_enumTypes[2].Descriptor()
}

func (PBListFolderItem_ItemType) Type() protoreflect.EnumType {
	return &file_internal_anylistpb_anylist_proto_enumTypes[2]
}

func (x PBListFolderItem_ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PBListFolderItem_ItemType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PBListFolderItem_ItemType(num)
	return nil
}

// Deprecated: Use PBListFolderItem_ItemType.Descriptor instead.
func (PBListFolderItem_ItemType) EnumDescriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{3, 0}
}

type PBOperationMetadata_OperationClass int32

const (
	PBOperationMetadata_UndefinedOperation              PBOperationMetadata_OperationClass = 0
	PBOperationMetadata_StoreOperation                  PBOperationMetadata_OperationClass = 1
	PBOperationMetadata_StoreFilterOperation            PBOperationMetadata_OperationClass = 2
	PBOperationMetadata_ListCategoryOperation           PBOperationMetadata_OperationClass = 3
	PBOperationMetadata_ListCategoryGroupOperation      PBOperationMetadata_OperationClass = 4
	PBOperationMetadata_ListCategorizationRuleOperation PBOperationMetadata_OperationClass = 5
)

// Enum value maps for PBOperationMetadata_OperationClass.
var (
	PBOperationMetadata_OperationClass_name = map[int32]string{
		0: "UndefinedOperation",
		1: "StoreOperation",
		2: "StoreFilterOperation",
		3: "ListCategoryOperation",
		4: "ListCategoryGroupOperation",
		5: "ListCategorizationRuleOperation",
	}
	PBOperationMetadata_OperationClass_value = map[string]int32{
		"UndefinedOperation":              0,
		"StoreOperation":                  1,
		"StoreFilterOperation":            2,
		"ListCategoryOperation":           3,
		"ListCategoryGroupOperation":      4,
		"ListCategorizationRuleOperation": 5,
	}
)

func (x PBOperationMetadata_OperationClass) Enum() *PBOperationMetadata_OperationClass {
	p := new(PBOperationMetadata_OperationClass)
	*p = x
	return p
}

func (x PBOperationMetadata_OperationClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PBOperationMetadata_OperationClass) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_anylistpb_anylist_proto_enumTypes[3].Descriptor()
}

func (PBOperationMetadata_OperationClass) Type() protoreflect.EnumType {
	return &file_internal_anylistpb_anylist_proto_enumTypes[3]
}

func (x PBOperationMetadata_OperationClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PBOperationMetadata_OperationClass) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PBOperationMetadata_OperationClass(num)
	return nil
}

// Deprecated: Use PBOperationMetadata_OperationClass.Descriptor instead.
func (PBOperationMetadata_OperationClass) EnumDescriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{13, 0}
}

type ShoppingList struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	Identifier                       *string                `protobuf:"bytes,1,req,name=identifier" json:"identifier,omitempty"`
	Timestamp                        *float64               `protobuf:"fixed64,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Name                             *string                `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Items                            []*ListItem            `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
	Creator                          *string                `protobuf:"bytes,5,opt,name=creator" json:"creator,omitempty"`
	SharedUsers                      []*PBEmailUserIDPair   `protobuf:"bytes,7,rep,name=sharedUsers" json:"sharedUsers,omitempty"`
	LogicalClockTime                 *uint64                `protobuf:"varint,10,opt,name=logicalClockTime" json:"logicalClockTime,omitempty"`
	AllowsMultipleListCategoryGroups *bool                  `protobuf:"varint,16,opt,name=allowsMultipleListCategoryGroups" json:"allowsMultipleListCategoryGroups,omitempty"`
	ListItemSortOrder                *int32                 `protobuf:"varint,17,opt,name=listItemSortOrder" json:"listItemSortOrder,omitempty"`
	NewListItemPosition              *int32                 `protobuf:"varint,18,opt,name=newListItemPosition" json:"newListItemPosition,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *ShoppingList) Reset() {
	*x = ShoppingList{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingList) ProtoMessage() {}

func (x *ShoppingList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingList.ProtoReflect.Descriptor instead.
func (*ShoppingList) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{0}
}

func (x *ShoppingList) GetIdentifier() string {
	if x != nil && x.Identifier != nil {
		return *x.Identifier
	}
	return ""
}

func (x *ShoppingList) GetTimestamp() float64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *ShoppingList) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ShoppingList) GetItems() []*ListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ShoppingList) GetCreator() string {
	if x != nil && x.Creator != nil {
		return *x.Creator
	}
	return ""
}

func (x *ShoppingList) GetSharedUsers() []*PBEmailUserIDPair {
	if x != nil {
		return x.SharedUsers
	}
	return nil
}

func (x *ShoppingList) GetLogicalClockTime() uint64 {
	if x != nil && x.LogicalClockTime != nil {
		return *x.LogicalClockTime
	}
	return 0
}

func (x *ShoppingList) GetAllowsMultipleListCategoryGroups() bool {
	if x != nil && x.AllowsMultipleListCategoryGroups != nil {
		return *x.AllowsMultipleListCategoryGroups
	}
	return false
}

func (x *ShoppingList) GetListItemSortOrder() int32 {
	if x != nil && x.ListItemSortOrder != nil {
		return *x.ListItemSortOrder
	}
	return 0
}

func (x *ShoppingList) GetNewListItemPosition() int32 {
	if x != nil && x.NewListItemPosition != nil {
		return *x.NewListItemPosition
	}
	return 0
}

type PBItemQuantity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        *string                `protobuf:"bytes,1,opt,name=amount" json:"amount,omitempty"`
	Unit          *string                `protobuf:"bytes,2,opt,name=unit" json:"unit,omitempty"`
	RawQuantity   *string                `protobuf:"bytes,3,opt,name=rawQuantity" json:"rawQuantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBItemQuantity) Reset() {
	*x = PBItemQuantity{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBItemQuantity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBItemQuantity) ProtoMessage() {}

func (x *PBItemQuantity) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBItemQuantity.ProtoReflect.Descriptor instead.
func (*PBItemQuantity) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{1}
}

func (x *PBItemQuantity) GetAmount() string {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return ""
}

func (x *PBItemQuantity) GetUnit() string {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return ""
}

func (x *PBItemQuantity) GetRawQuantity() string {
	if x != nil && x.RawQuantity != nil {
		return *x.RawQuantity
	}
	return ""
}

type ListItem struct {
	state               protoimpl.MessageState          `protogen:"open.v1"`
	Identifier          *string                         `protobuf:"bytes,1,req,name=identifier" json:"identifier,omitempty"`
	ServerModTime       *float64                        `protobuf:"fixed64,2,opt,name=serverModTime" json:"serverModTime,omitempty"`
	ListId              *string                         `protobuf:"bytes,3,opt,name=listId" json:"listId,omitempty"`
	Name                *string                         `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Details             *string                         `protobuf:"bytes,5,opt,name=details" json:"details,omitempty"`
	Checked             *bool                           `protobuf:"varint,6,opt,name=checked" json:"checked,omitempty"`
	Category            *string                         `protobuf:"bytes,11,opt,name=category" json:"category,omitempty"`
	UserId              *string                         `protobuf:"bytes,12,opt,name=userId" json:"userId,omitempty"`
	CategoryMatchId     *string                         `protobuf:"bytes,13,opt,name=categoryMatchId" json:"categoryMatchId,omitempty"`
	CategoryAssignments []*PBListItemCategoryAssignment `protobuf:"bytes,20,rep,name=categoryAssignments" json:"categoryAssignments,omitempty"`
	QuantityPb          *PBItemQuantity                 `protobuf:"bytes,21,opt,name=quantityPb" json:"quantityPb,omitempty"`
	ManualSortIndex     *int32                          `protobuf:"varint,17,opt,name=manualSortIndex" json:"manualSortIndex,omitempty"`
	DeprecatedQuantity  *string                         `protobuf:"bytes,18,opt,name=deprecatedQuantity" json:"deprecatedQuantity,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListItem) Reset() {
	*x = ListItem{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItem) ProtoMessage() {}

func (x *ListItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItem.ProtoReflect.Descriptor instead.
func (*ListItem) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{2}
}

func (x *ListItem) GetIdentifier() string {
	if x != nil && x.Identifier != nil {
		return *x.Identifier
	}
	return ""
}

func (x *ListItem) GetServerModTime() float64 {
	if x != nil && x.ServerModTime != nil {
		return *x.ServerModTime
	}
	return 0
}

func (x *ListItem) GetListId() string {
	if x != nil && x.ListId != nil {
		return *x.ListId
	}
	return ""
}

func (x *ListItem) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ListItem) GetDetails() string {
	if x != nil && x.Details != nil {
		return *x.Details
	}
	return ""
}

func (x *ListItem) GetChecked() bool {
	if x != nil && x.Checked != nil {
		return *x.Checked
	}
	return false
}

func (x *ListItem) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *ListItem) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *ListItem) GetCategoryMatchId() string {
	if x != nil && x.CategoryMatchId != nil {
		return *x.CategoryMatchId
	}
	return ""
}

func (x *ListItem) GetCategoryAssignments() []*PBListItemCategoryAssignment {
	if x != nil {
		return x.CategoryAssignments
	}
	return nil
}

func (x *ListItem) GetQuantityPb() *PBItemQuantity {
	if x != nil {
		return x.QuantityPb
	}
	return nil
}

func (x *ListItem) GetManualSortIndex() int32 {
	if x != nil && x.ManualSortIndex != nil {
		return *x.ManualSortIndex
	}
	return 0
}

func (x *ListItem) GetDeprecatedQuantity() string {
	if x != nil && x.DeprecatedQuantity != nil {
		return *x.DeprecatedQuantity
	}
	return ""
}

type PBListFolderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *string                `protobuf:"bytes,1,req,name=identifier" json:"identifier,omitempty"`
	ItemType      *int32                 `protobuf:"varint,2,opt,name=itemType" json:"itemType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBListFolderItem) Reset() {
	*x = PBListFolderItem{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListFolderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListFolderItem) ProtoMessage() {}

func (x *PBListFolderItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListFolderItem.ProtoReflect.Descriptor instead.
func (*PBListFolderItem) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{3}
}

func (x *PBListFolderItem) GetIdentifier() string {
	if x != nil && x.Identifier != nil {
		return *x.Identifier
	}
	return ""
}

func (x *PBListFolderItem) GetItemType() int32 {
	if x != nil && x.ItemType != nil {
		return *x.ItemType
	}
	return 0
}

type PBListFolder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *string                `protobuf:"bytes,1,req,name=identifier" json:"identifier,omitempty"`
	Timestamp     *float64               `protobuf:"fixed64,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Items         []*PBListFolderItem    `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBListFolder) Reset() {
	*x = PBListFolder{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListFolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListFolder) ProtoMessage() {}

func (x *PBListFolder) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListFolder.ProtoReflect.Descriptor instead.
func (*PBListFolder) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{4}
}

func (x *PBListFolder) GetIdentifier() string {
	if x != nil && x.Identifier != nil {
		return *x.Identifier
	}
	return ""
}

func (x *PBListFolder) GetTimestamp() float64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *PBListFolder) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PBListFolder) GetItems() []*PBListFolderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PBListFoldersResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ListDataId              *string                `protobuf:"bytes,1,opt,name=listDataId" json:"listDataId,omitempty"`
	RootFolderId            *string                `protobuf:"bytes,2,opt,name=rootFolderId" json:"rootFolderId,omitempty"`
	IncludesAllFolders      *bool                  `protobuf:"varint,3,opt,name=includesAllFolders" json:"includesAllFolders,omitempty"`
	ListFolders             []*PBListFolder        `protobuf:"bytes,4,rep,name=listFolders" json:"listFolders,omitempty"`
	DeletedFolderIds        []string               `protobuf:"bytes,5,rep,name=deletedFolderIds" json:"deletedFolderIds,omitempty"`
	HasMigratedListOrdering *bool                  `protobuf:"varint,6,opt,name=hasMigratedListOrdering" json:"hasMigratedListOrdering,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PBListFoldersResponse) Reset() {
	*x = PBListFoldersResponse{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListFoldersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListFoldersResponse) ProtoMessage() {}

func (x *PBListFoldersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListFoldersResponse.ProtoReflect.Descriptor instead.
func (*PBListFoldersResponse) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{5}
}

func (x *PBListFoldersResponse) GetListDataId() string {
	if x != nil && x.ListDataId != nil {
		return *x.ListDataId
	}
	return ""
}

func (x *PBListFoldersResponse) GetRootFolderId() string {
	if x != nil && x.RootFolderId != nil {
		return *x.RootFolderId
	}
	return ""
}

func (x *PBListFoldersResponse) GetIncludesAllFolders() bool {
	if x != nil && x.IncludesAllFolders != nil {
		return *x.IncludesAllFolders
	}
	return false
}

func (x *PBListFoldersResponse) GetListFolders() []*PBListFolder {
	if x != nil {
		return x.ListFolders
	}
	return nil
}

func (x *PBListFoldersResponse) GetDeletedFolderIds() []string {
	if x != nil {
		return x.DeletedFolderIds
	}
	return nil
}

func (x *PBListFoldersResponse) GetHasMigratedListOrdering() bool {
	if x != nil && x.HasMigratedListOrdering != nil {
		return *x.HasMigratedListOrdering
	}
	return false
}

type PBListCategoryGroupResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CategoryGroup      *PBListCategoryGroup   `protobuf:"bytes,1,opt,name=categoryGroup" json:"categoryGroup,omitempty"`
	DeletedCategoryIds []string               `protobuf:"bytes,2,rep,name=deletedCategoryIds" json:"deletedCategoryIds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PBListCategoryGroupResponse) Reset() {
	*x = PBListCategoryGroupResponse{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListCategoryGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListCategoryGroupResponse) ProtoMessage() {}

func (x *PBListCategoryGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListCategoryGroupResponse.ProtoReflect.Descriptor instead.
func (*PBListCategoryGroupResponse) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{6}
}

func (x *PBListCategoryGroupResponse) GetCategoryGroup() *PBListCategoryGroup {
	if x != nil {
		return x.CategoryGroup
	}
	return nil
}

func (x *PBListCategoryGroupResponse) GetDeletedCategoryIds() []string {
	if x != nil {
		return x.DeletedCategoryIds
	}
	return nil
}

type ShoppingListsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewLists      []*ShoppingList        `protobuf:"bytes,1,rep,name=newLists" json:"newLists,omitempty"`
	ModifiedLists []*ShoppingList        `protobuf:"bytes,2,rep,name=modifiedLists" json:"modifiedLists,omitempty"`
	UnmodifiedIds []string               `protobuf:"bytes,3,rep,name=unmodifiedIds" json:"unmodifiedIds,omitempty"`
	UnknownIds    []string               `protobuf:"bytes,4,rep,name=unknownIds" json:"unknownIds,omitempty"`
	OrderedIds    []string               `protobuf:"bytes,5,rep,name=orderedIds" json:"orderedIds,omitempty"`
	ListResponses []*PBListResponse      `protobuf:"bytes,6,rep,name=listResponses" json:"listResponses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShoppingListsResponse) Reset() {
	*x = ShoppingListsResponse{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingListsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingListsResponse) ProtoMessage() {}

func (x *ShoppingListsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingListsResponse.ProtoReflect.Descriptor instead.
func (*ShoppingListsResponse) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{7}
}

func (x *ShoppingListsResponse) GetNewLists() []*ShoppingList {
	if x != nil {
		return x.NewLists
	}
	return nil
}

func (x *ShoppingListsResponse) GetModifiedLists() []*ShoppingList {
	if x != nil {
		return x.ModifiedLists
	}
	return nil
}

func (x *ShoppingListsResponse) GetUnmodifiedIds() []string {
	if x != nil {
		return x.UnmodifiedIds
	}
	return nil
}

func (x *ShoppingListsResponse) GetUnknownIds() []string {
	if x != nil {
		return x.UnknownIds
	}
	return nil
}

func (x *ShoppingListsResponse) GetOrderedIds() []string {
	if x != nil {
		return x.OrderedIds
	}
	return nil
}

func (x *ShoppingListsResponse) GetListResponses() []*PBListResponse {
	if x != nil {
		return x.ListResponses
	}
	return nil
}

type PBListResponse struct {
	state                   protoimpl.MessageState         `protogen:"open.v1"`
	ListId                  *string                        `protobuf:"bytes,1,opt,name=listId" json:"listId,omitempty"`
	IsFullSync              *bool                          `protobuf:"varint,2,opt,name=isFullSync" json:"isFullSync,omitempty"`
	LogicalTimestamp        *uint64                        `protobuf:"varint,3,opt,name=logicalTimestamp" json:"logicalTimestamp,omitempty"`
	CategoryGroupResponses  []*PBListCategoryGroupResponse `protobuf:"bytes,7,rep,name=categoryGroupResponses" json:"categoryGroupResponses,omitempty"`
	DeletedCategoryGroupIds []string                       `protobuf:"bytes,8,rep,name=deletedCategoryGroupIds" json:"deletedCategoryGroupIds,omitempty"`
	StoreFilters            []*PBStoreFilter               `protobuf:"bytes,11,rep,name=storeFilters" json:"storeFilters,omitempty"`
	DeletedStoreFilterIds   []string                       `protobuf:"bytes,12,rep,name=deletedStoreFilterIds" json:"deletedStoreFilterIds,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PBListResponse) Reset() {
	*x = PBListResponse{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListResponse) ProtoMessage() {}

func (x *PBListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListResponse.ProtoReflect.Descriptor instead.
func (*PBListResponse) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{8}
}

func (x *PBListResponse) GetListId() string {
	if x != nil && x.ListId != nil {
		return *x.ListId
	}
	return ""
}

func (x *PBListResponse) GetIsFullSync() bool {
	if x != nil && x.IsFullSync != nil {
		return *x.IsFullSync
	}
	return false
}

func (x *PBListResponse) GetLogicalTimestamp() uint64 {
	if x != nil && x.LogicalTimestamp != nil {
		return *x.LogicalTimestamp
	}
	return 0
}

func (x *PBListResponse) GetCategoryGroupResponses() []*PBListCategoryGroupResponse {
	if x != nil {
		return x.CategoryGroupResponses
	}
	return nil
}

func (x *PBListResponse) GetDeletedCategoryGroupIds() []string {
	if x != nil {
		return x.DeletedCategoryGroupIds
	}
	return nil
}

func (x *PBListResponse) GetStoreFilters() []*PBStoreFilter {
	if x != nil {
		return x.StoreFilters
	}
	return nil
}

func (x *PBListResponse) GetDeletedStoreFilterIds() []string {
	if x != nil {
		return x.DeletedStoreFilterIds
	}
	return nil
}

type PBStoreFilter struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Identifier          *string                `protobuf:"bytes,1,req,name=identifier" json:"identifier,omitempty"`
	ListId              *string                `protobuf:"bytes,3,opt,name=listId" json:"listId,omitempty"`
	ListCategoryGroupId *string                `protobuf:"bytes,8,opt,name=listCategoryGroupId" json:"listCategoryGroupId,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PBStoreFilter) Reset() {
	*x = PBStoreFilter{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBStoreFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBStoreFilter) ProtoMessage() {}

func (x *PBStoreFilter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBStoreFilter.ProtoReflect.Descriptor instead.
func (*PBStoreFilter) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{9}
}

func (x *PBStoreFilter) GetIdentifier() string {
	if x != nil && x.Identifier != nil {
		return *x.Identifier
	}
	return ""
}

func (x *PBStoreFilter) GetListId() string {
	if x != nil && x.ListId != nil {
		return *x.ListId
	}
	return ""
}

func (x *PBStoreFilter) GetListCategoryGroupId() string {
	if x != nil && x.ListCategoryGroupId != nil {
		return *x.ListCategoryGroupId
	}
	return ""
}

type PBListCategory struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Identifier       *string                `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	LogicalTimestamp *uint64                `protobuf:"varint,2,opt,name=logicalTimestamp" json:"logicalTimestamp,omitempty"`
	CategoryGroupId  *string                `protobuf:"bytes,3,opt,name=categoryGroupId" json:"categoryGroupId,omitempty"`
	ListId           *string                `protobuf:"bytes,4,opt,name=listId" json:"listId,omitempty"`
	Name             *string                `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Icon             *string                `protobuf:"bytes,6,opt,name=icon" json:"icon,omitempty"`
	SystemCategory   *string                `protobuf:"bytes,7,opt,name=systemCategory" json:"systemCategory,omitempty"`
	SortIndex        *int32                 `protobuf:"varint,9,opt,name=sortIndex" json:"sortIndex,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PBListCategory) Reset() {
	*x = PBListCategory{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListCategory) ProtoMessage() {}

func (x *PBListCategory) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListCategory.ProtoReflect.Descriptor instead.
func (*PBListCategory) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{10}
}

func (x *PBListCategory) GetIdentifier() string {
	if x != nil && x.Identifier != nil {
		return *x.Identifier
	}
	return ""
}

func (x *PBListCategory) GetLogicalTimestamp() uint64 {
	if x != nil && x.LogicalTimestamp != nil {
		return *x.LogicalTimestamp
	}
	return 0
}

func (x *PBListCategory) GetCategoryGroupId() string {
	if x != nil && x.CategoryGroupId != nil {
		return *x.CategoryGroupId
	}
	return ""
}

func (x *PBListCategory) GetListId() string {
	if x != nil && x.ListId != nil {
		return *x.ListId
	}
	return ""
}

func (x *PBListCategory) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PBListCategory) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *PBListCategory) GetSystemCategory() string {
	if x != nil && x.SystemCategory != nil {
		return *x.SystemCategory
	}
	return ""
}

func (x *PBListCategory) GetSortIndex() int32 {
	if x != nil && x.SortIndex != nil {
		return *x.SortIndex
	}
	return 0
}

type PBListCategoryGroup struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	Identifier                        *string                `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	LogicalTimestamp                  *uint64                `protobuf:"varint,2,opt,name=logicalTimestamp" json:"logicalTimestamp,omitempty"`
	ListId                            *string                `protobuf:"bytes,3,opt,name=listId" json:"listId,omitempty"`
	Name                              *string                `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Categories                        []*PBListCategory      `protobuf:"bytes,5,rep,name=categories" json:"categories,omitempty"`
	DefaultCategoryId                 *string                `protobuf:"bytes,8,opt,name=defaultCategoryId" json:"defaultCategoryId,omitempty"`
	CategoriesLogicalTimestamp        *uint64                `protobuf:"varint,6,opt,name=categoriesLogicalTimestamp" json:"categoriesLogicalTimestamp,omitempty"`
	DeletedCategoriesLogicalTimestamp *uint64                `protobuf:"varint,7,opt,name=deletedCategoriesLogicalTimestamp" json:"deletedCategoriesLogicalTimestamp,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *PBListCategoryGroup) Reset() {
	*x = PBListCategoryGroup{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListCategoryGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListCategoryGroup) ProtoMessage() {}

func (x *PBListCategoryGroup) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListCategoryGroup.ProtoReflect.Descriptor instead.
func (*PBListCategoryGroup) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{11}
}

func (x *PBListCategoryGroup) GetIdentifier() string {
	if x != nil && x.Identifier != nil {
		return *x.Identifier
	}
	return ""
}

func (x *PBListCategoryGroup) GetLogicalTimestamp() uint64 {
	if x != nil && x.LogicalTimestamp != nil {
		return *x.LogicalTimestamp
	}
	return 0
}

func (x *PBListCategoryGroup) GetListId() string {
	if x != nil && x.ListId != nil {
		return *x.ListId
	}
	return ""
}

func (x *PBListCategoryGroup) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PBListCategoryGroup) GetCategories() []*PBListCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *PBListCategoryGroup) GetDefaultCategoryId() string {
	if x != nil && x.DefaultCategoryId != nil {
		return *x.DefaultCategoryId
	}
	return ""
}

func (x *PBListCategoryGroup) GetCategoriesLogicalTimestamp() uint64 {
	if x != nil && x.CategoriesLogicalTimestamp != nil {
		return *x.CategoriesLogicalTimestamp
	}
	return 0
}

func (x *PBListCategoryGroup) GetDeletedCategoriesLogicalTimestamp() uint64 {
	if x != nil && x.DeletedCategoriesLogicalTimestamp != nil {
		return *x.DeletedCategoriesLogicalTimestamp
	}
	return 0
}

type PBListItemCategoryAssignment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Identifier      *string                `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	CategoryGroupId *string                `protobuf:"bytes,2,opt,name=categoryGroupId" json:"categoryGroupId,omitempty"`
	CategoryId      *string                `protobuf:"bytes,3,opt,name=categoryId" json:"categoryId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PBListItemCategoryAssignment) Reset() {
	*x = PBListItemCategoryAssignment{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListItemCategoryAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListItemCategoryAssignment) ProtoMessage() {}

func (x *PBListItemCategoryAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListItemCategoryAssignment.ProtoReflect.Descriptor instead.
func (*PBListItemCategoryAssignment) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{12}
}

func (x *PBListItemCategoryAssignment) GetIdentifier() string {
	if x != nil && x.Identifier != nil {
		return *x.Identifier
	}
	return ""
}

func (x *PBListItemCategoryAssignment) GetCategoryGroupId() string {
	if x != nil && x.CategoryGroupId != nil {
		return *x.CategoryGroupId
	}
	return ""
}

func (x *PBListItemCategoryAssignment) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

type PBOperationMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationId      *string                `protobuf:"bytes,1,opt,name=operationId" json:"operationId,omitempty"`
	HandlerId        *string                `protobuf:"bytes,2,opt,name=handlerId" json:"handlerId,omitempty"`
	UserId           *string                `protobuf:"bytes,3,opt,name=userId" json:"userId,omitempty"`
	OperationClass   *int32                 `protobuf:"varint,4,opt,name=operationClass" json:"operationClass,omitempty"`
	OperationVersion *int32                 `protobuf:"varint,5,opt,name=operationVersion" json:"operationVersion,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PBOperationMetadata) Reset() {
	*x = PBOperationMetadata{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBOperationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBOperationMetadata) ProtoMessage() {}

func (x *PBOperationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBOperationMetadata.ProtoReflect.Descriptor instead.
func (*PBOperationMetadata) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{13}
}

func (x *PBOperationMetadata) GetOperationId() string {
	if x != nil && x.OperationId != nil {
		return *x.OperationId
	}
	return ""
}

func (x *PBOperationMetadata) GetHandlerId() string {
	if x != nil && x.HandlerId != nil {
		return *x.HandlerId
	}
	return ""
}

func (x *PBOperationMetadata) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *PBOperationMetadata) GetOperationClass() int32 {
	if x != nil && x.OperationClass != nil {
		return *x.OperationClass
	}
	return 0
}

func (x *PBOperationMetadata) GetOperationVersion() int32 {
	if x != nil && x.OperationVersion != nil {
		return *x.OperationVersion
	}
	return 0
}

type PBListOperation struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Metadata             *PBOperationMetadata   `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	ListId               *string                `protobuf:"bytes,2,opt,name=listId" json:"listId,omitempty"`
	ListItemId           *string                `protobuf:"bytes,3,opt,name=listItemId" json:"listItemId,omitempty"`
	UpdatedValue         *string                `protobuf:"bytes,4,opt,name=updatedValue" json:"updatedValue,omitempty"`
	OriginalValue        *string                `protobuf:"bytes,5,opt,name=originalValue" json:"originalValue,omitempty"`
	ListItem             *ListItem              `protobuf:"bytes,6,opt,name=listItem" json:"listItem,omitempty"`
	List                 *ShoppingList          `protobuf:"bytes,7,opt,name=list" json:"list,omitempty"`
	ListFolderId         *string                `protobuf:"bytes,8,opt,name=listFolderId" json:"listFolderId,omitempty"`
	UpdatedCategoryGroup *PBListCategoryGroup   `protobuf:"bytes,19,opt,name=updatedCategoryGroup" json:"updatedCategoryGroup,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PBListOperation) Reset() {
	*x = PBListOperation{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListOperation) ProtoMessage() {}

func (x *PBListOperation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListOperation.ProtoReflect.Descriptor instead.
func (*PBListOperation) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{14}
}

func (x *PBListOperation) GetMetadata() *PBOperationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PBListOperation) GetListId() string {
	if x != nil && x.ListId != nil {
		return *x.ListId
	}
	return ""
}

func (x *PBListOperation) GetListItemId() string {
	if x != nil && x.ListItemId != nil {
		return *x.ListItemId
	}
	return ""
}

func (x *PBListOperation) GetUpdatedValue() string {
	if x != nil && x.UpdatedValue != nil {
		return *x.UpdatedValue
	}
	return ""
}

func (x *PBListOperation) GetOriginalValue() string {
	if x != nil && x.OriginalValue != nil {
		return *x.OriginalValue
	}
	return ""
}

func (x *PBListOperation) GetListItem() *ListItem {
	if x != nil {
		return x.ListItem
	}
	return nil
}

func (x *PBListOperation) GetList() *ShoppingList {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *PBListOperation) GetListFolderId() string {
	if x != nil && x.ListFolderId != nil {
		return *x.ListFolderId
	}
	return ""
}

func (x *PBListOperation) GetUpdatedCategoryGroup() *PBListCategoryGroup {
	if x != nil {
		return x.UpdatedCategoryGroup
	}
	return nil
}

type PBListOperationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*PBListOperation     `protobuf:"bytes,1,rep,name=operations" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBListOperationList) Reset() {
	*x = PBListOperationList{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListOperationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListOperationList) ProtoMessage() {}

func (x *PBListOperationList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListOperationList.ProtoReflect.Descriptor instead.
func (*PBListOperationList) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{15}
}

func (x *PBListOperationList) GetOperations() []*PBListOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type PBShareListOperationResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SharedUser            *PBEmailUserIDPair     `protobuf:"bytes,1,opt,name=sharedUser" json:"sharedUser,omitempty"`
	OriginalListTimestamp *float64               `protobuf:"fixed64,2,opt,name=originalListTimestamp" json:"originalListTimestamp,omitempty"`
	UpdatedListTimestamp  *float64               `protobuf:"fixed64,3,opt,name=updatedListTimestamp" json:"updatedListTimestamp,omitempty"`
	StatusCode            *int32                 `protobuf:"varint,4,opt,name=statusCode" json:"statusCode,omitempty"`
	ErrorTitle            *string                `protobuf:"bytes,5,opt,name=errorTitle" json:"errorTitle,omitempty"`
	ErrorMessage          *string                `protobuf:"bytes,6,opt,name=errorMessage" json:"errorMessage,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PBShareListOperationResponse) Reset() {
	*x = PBShareListOperationResponse{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBShareListOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBShareListOperationResponse) ProtoMessage() {}

func (x *PBShareListOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBShareListOperationResponse.ProtoReflect.Descriptor instead.
func (*PBShareListOperationResponse) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{16}
}

func (x *PBShareListOperationResponse) GetSharedUser() *PBEmailUserIDPair {
	if x != nil {
		return x.SharedUser
	}
	return nil
}

func (x *PBShareListOperationResponse) GetOriginalListTimestamp() float64 {
	if x != nil && x.OriginalListTimestamp != nil {
		return *x.OriginalListTimestamp
	}
	return 0
}

func (x *PBShareListOperationResponse) GetUpdatedListTimestamp() float64 {
	if x != nil && x.UpdatedListTimestamp != nil {
		return *x.UpdatedListTimestamp
	}
	return 0
}

func (x *PBShareListOperationResponse) GetStatusCode() int32 {
	if x != nil && x.StatusCode != nil {
		return *x.StatusCode
	}
	return 0
}

func (x *PBShareListOperationResponse) GetErrorTitle() string {
	if x != nil && x.ErrorTitle != nil {
		return *x.ErrorTitle
	}
	return ""
}

func (x *PBShareListOperationResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type PBListFolderOperation struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Metadata               *PBOperationMetadata   `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	ListDataId             *string                `protobuf:"bytes,2,opt,name=listDataId" json:"listDataId,omitempty"`
	FolderItems            []*PBListFolderItem    `protobuf:"bytes,4,rep,name=folderItems" json:"folderItems,omitempty"`
	OriginalParentFolderId *string                `protobuf:"bytes,5,opt,name=originalParentFolderId" json:"originalParentFolderId,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PBListFolderOperation) Reset() {
	*x = PBListFolderOperation{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListFolderOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListFolderOperation) ProtoMessage() {}

func (x *PBListFolderOperation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListFolderOperation.ProtoReflect.Descriptor instead.
func (*PBListFolderOperation) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{17}
}

func (x *PBListFolderOperation) GetMetadata() *PBOperationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PBListFolderOperation) GetListDataId() string {
	if x != nil && x.ListDataId != nil {
		return *x.ListDataId
	}
	return ""
}

func (x *PBListFolderOperation) GetFolderItems() []*PBListFolderItem {
	if x != nil {
		return x.FolderItems
	}
	return nil
}

func (x *PBListFolderOperation) GetOriginalParentFolderId() string {
	if x != nil && x.OriginalParentFolderId != nil {
		return *x.OriginalParentFolderId
	}
	return ""
}

type PBListFolderOperationList struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Operations    []*PBListFolderOperation `protobuf:"bytes,1,rep,name=operations" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBListFolderOperationList) Reset() {
	*x = PBListFolderOperationList{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListFolderOperationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListFolderOperationList) ProtoMessage() {}

func (x *PBListFolderOperationList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListFolderOperationList.ProtoReflect.Descriptor instead.
func (*PBListFolderOperationList) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{18}
}

func (x *PBListFolderOperationList) GetOperations() []*PBListFolderOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type PBListSettings struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Identifier          *string                `protobuf:"bytes,1,req,name=identifier" json:"identifier,omitempty"`
	UserId              *string                `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
	ListId              *string                `protobuf:"bytes,3,opt,name=listId" json:"listId,omitempty"`
	Timestamp           *float64               `protobuf:"fixed64,4,opt,name=timestamp" json:"timestamp,omitempty"`
	StoreFilterId       *string                `protobuf:"bytes,20,opt,name=storeFilterId" json:"storeFilterId,omitempty"`
	ListCategoryGroupId *string                `protobuf:"bytes,27,opt,name=listCategoryGroupId" json:"listCategoryGroupId,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PBListSettings) Reset() {
	*x = PBListSettings{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListSettings) ProtoMessage() {}

func (x *PBListSettings) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListSettings.ProtoReflect.Descriptor instead.
func (*PBListSettings) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{19}
}

func (x *PBListSettings) GetIdentifier() string {
	if x != nil && x.Identifier != nil {
		return *x.Identifier
	}
	return ""
}

func (x *PBListSettings) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *PBListSettings) GetListId() string {
	if x != nil && x.ListId != nil {
		return *x.ListId
	}
	return ""
}

func (x *PBListSettings) GetTimestamp() float64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *PBListSettings) GetStoreFilterId() string {
	if x != nil && x.StoreFilterId != nil {
		return *x.StoreFilterId
	}
	return ""
}

func (x *PBListSettings) GetListCategoryGroupId() string {
	if x != nil && x.ListCategoryGroupId != nil {
		return *x.ListCategoryGroupId
	}
	return ""
}

type PBListSettingsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      []*PBListSettings      `protobuf:"bytes,2,rep,name=settings" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBListSettingsList) Reset() {
	*x = PBListSettingsList{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListSettingsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListSettingsList) ProtoMessage() {}

func (x *PBListSettingsList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListSettingsList.ProtoReflect.Descriptor instead.
func (*PBListSettingsList) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{20}
}

func (x *PBListSettingsList) GetSettings() []*PBListSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type PBListSettingsOperation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Metadata        *PBOperationMetadata   `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	UpdatedSettings *PBListSettings        `protobuf:"bytes,2,opt,name=updatedSettings" json:"updatedSettings,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PBListSettingsOperation) Reset() {
	*x = PBListSettingsOperation{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListSettingsOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListSettingsOperation) ProtoMessage() {}

func (x *PBListSettingsOperation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListSettingsOperation.ProtoReflect.Descriptor instead.
func (*PBListSettingsOperation) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{21}
}

func (x *PBListSettingsOperation) GetMetadata() *PBOperationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PBListSettingsOperation) GetUpdatedSettings() *PBListSettings {
	if x != nil {
		return x.UpdatedSettings
	}
	return nil
}

type PBListSettingsOperationList struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Operations    []*PBListSettingsOperation `protobuf:"bytes,1,rep,name=operations" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBListSettingsOperationList) Reset() {
	*x = PBListSettingsOperationList{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListSettingsOperationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListSettingsOperationList) ProtoMessage() {}

func (x *PBListSettingsOperationList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListSettingsOperationList.ProtoReflect.Descriptor instead.
func (*PBListSettingsOperationList) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{22}
}

func (x *PBListSettingsOperationList) GetOperations() []*PBListSettingsOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type PBEditOperationResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProcessedOperations []string               `protobuf:"bytes,3,rep,name=processedOperations" json:"processedOperations,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PBEditOperationResponse) Reset() {
	*x = PBEditOperationResponse{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBEditOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBEditOperationResponse) ProtoMessage() {}

func (x *PBEditOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBEditOperationResponse.ProtoReflect.Descriptor instead.
func (*PBEditOperationResponse) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{23}
}

func (x *PBEditOperationResponse) GetProcessedOperations() []string {
	if x != nil {
		return x.ProcessedOperations
	}
	return nil
}

type PBEmailUserIDPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *string                `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	UserId        *string                `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
	FullName      *string                `protobuf:"bytes,3,opt,name=fullName" json:"fullName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBEmailUserIDPair) Reset() {
	*x = PBEmailUserIDPair{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBEmailUserIDPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBEmailUserIDPair) ProtoMessage() {}

func (x *PBEmailUserIDPair) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBEmailUserIDPair.ProtoReflect.Descriptor instead.
func (*PBEmailUserIDPair) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{24}
}

func (x *PBEmailUserIDPair) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *PBEmailUserIDPair) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *PBEmailUserIDPair) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

type PBUserDataResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ShoppingListsResponse *ShoppingListsResponse `protobuf:"bytes,1,opt,name=shoppingListsResponse" json:"shoppingListsResponse,omitempty"`
	ListFoldersResponse   *PBListFoldersResponse `protobuf:"bytes,2,opt,name=listFoldersResponse" json:"listFoldersResponse,omitempty"`
	ListSettingsResponse  *PBListSettingsList    `protobuf:"bytes,9,opt,name=listSettingsResponse" json:"listSettingsResponse,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PBUserDataResponse) Reset() {
	*x = PBUserDataResponse{}
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBUserDataResponse) ProtoMessage() {}

func (x *PBUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_anylistpb_anylist_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBUserDataResponse.ProtoReflect.Descriptor instead.
func (*PBUserDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_anylistpb_anylist_proto_rawDescGZIP(), []int{25}
}

func (x *PBUserDataResponse) GetShoppingListsResponse() *ShoppingListsResponse {
	if x != nil {
		return x.ShoppingListsResponse
	}
	return nil
}

func (x *PBUserDataResponse) GetListFoldersResponse() *PBListFoldersResponse {
	if x != nil {
		return x.ListFoldersResponse
	}
	return nil
}

func (x *PBUserDataResponse) GetListSettingsResponse() *PBListSettingsList {
	if x != nil {
		return x.ListSettingsResponse
	}
	return nil
}

var File_internal_anylistpb_anylist_proto protoreflect.FileDescriptor

const file_internal_anylistpb_anylist_proto_rawDesc = "" +
	"\n" +
	" internal/anylistpb/anylist.proto\x12\n" +
	"pcov.proto\"\x9e\x04\n" +
	"\fShoppingList\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x02(\tR\n" +
	"identifier\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x01R\ttimestamp\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12*\n" +
	"\x05items\x18\x04 \x03(\v2\x14.pcov.proto.ListItemR\x05items\x12\x18\n" +
	"\acreator\x18\x05 \x01(\tR\acreator\x12?\n" +
	"\vsharedUsers\x18\a \x03(\v2\x1d.pcov.proto.PBEmailUserIDPairR\vsharedUsers\x12*\n" +
	"\x10logicalClockTime\x18\n" +
	" \x01(\x04R\x10logicalClockTime\x12J\n" +
	" allowsMultipleListCategoryGroups\x18\x10 \x01(\bR allowsMultipleListCategoryGroups\x12,\n" +
	"\x11listItemSortOrder\x18\x11 \x01(\x05R\x11listItemSortOrder\x120\n" +
	"\x13newListItemPosition\x18\x12 \x01(\x05R\x13newListItemPosition\"1\n" +
	"\x11ListItemSortOrder\x12\n" +
	"\n" +
	"\x06Manual\x10\x00\x12\x10\n" +
	"\fAlphabetical\x10\x01\"*\n" +
	"\x13NewListItemPosition\x12\n" +
	"\n" +
	"\x06Bottom\x10\x00\x12\a\n" +
	"\x03Top\x10\x01\"^\n" +
	"\x0ePBItemQuantity\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12 \n" +
	"\vrawQuantity\x18\x03 \x01(\tR\vrawQuantity\"\x80\x04\n" +
	"\bListItem\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x02(\tR\n" +
	"identifier\x12$\n" +
	"\rserverModTime\x18\x02 \x01(\x01R\rserverModTime\x12\x16\n" +
	"\x06listId\x18\x03 \x01(\tR\x06listId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\adetails\x18\x05 \x01(\tR\adetails\x12\x18\n" +
	"\achecked\x18\x06 \x01(\bR\achecked\x12\x1a\n" +
	"\bcategory\x18\v \x01(\tR\bcategory\x12\x16\n" +
	"\x06userId\x18\f \x01(\tR\x06userId\x12(\n" +
	"\x0fcategoryMatchId\x18\r \x01(\tR\x0fcategoryMatchId\x12Z\n" +
	"\x13categoryAssignments\x18\x14 \x03(\v2(.pcov.proto.PBListItemCategoryAssignmentR\x13categoryAssignments\x12:\n" +
	"\n" +
	"quantityPb\x18\x15 \x01(\v2\x1a.pcov.proto.PBItemQuantityR\n" +
	"quantityPb\x12(\n" +
	"\x0fmanualSortIndex\x18\x11 \x01(\x05R\x0fmanualSortIndex\x12.\n" +
	"\x12deprecatedQuantity\x18\x12 \x01(\tR\x12deprecatedQuantity\"x\n" +
	"\x10PBListFolderItem\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x02(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bitemType\x18\x02 \x01(\x05R\bitemType\"(\n" +
	"\bItemType\x12\f\n" +
	"\bListType\x10\x00\x12\x0e\n" +
	"\n" +
	"FolderType\x10\x01\"\x94\x01\n" +
	"\fPBListFolder\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x02(\tR\n" +
	"identifier\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x01R\ttimestamp\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x122\n" +
	"\x05items\x18\x04 \x03(\v2\x1c.pcov.proto.PBListFolderItemR\x05items\"\xad\x02\n" +
	"\x15PBListFoldersResponse\x12\x1e\n" +
	"\n" +
	"listDataId\x18\x01 \x01(\tR\n" +
	"listDataId\x12\"\n" +
	"\frootFolderId\x18\x02 \x01(\tR\frootFolderId\x12.\n" +
	"\x12includesAllFolders\x18\x03 \x01(\bR\x12includesAllFolders\x12:\n" +
	"\vlistFolders\x18\x04 \x03(\v2\x18.pcov.proto.PBListFolderR\vlistFolders\x12*\n" +
	"\x10deletedFolderIds\x18\x05 \x03(\tR\x10deletedFolderIds\x128\n" +
	"\x17hasMigratedListOrdering\x18\x06 \x01(\bR\x17hasMigratedListOrdering\"\x94\x01\n" +
	"\x1bPBListCategoryGroupResponse\x12E\n" +
	"\rcategoryGroup\x18\x01 \x01(\v2\x1f.pcov.proto.PBListCategoryGroupR\rcategoryGroup\x12.\n" +
	"\x12deletedCategoryIds\x18\x02 \x03(\tR\x12deletedCategoryIds\"\xb5\x02\n" +
	"\x15ShoppingListsResponse\x124\n" +
	"\bnewLists\x18\x01 \x03(\v2\x18.pcov.proto.ShoppingListR\bnewLists\x12>\n" +
	"\rmodifiedLists\x18\x02 \x03(\v2\x18.pcov.proto.ShoppingListR\rmodifiedLists\x12$\n" +
	"\runmodifiedIds\x18\x03 \x03(\tR\runmodifiedIds\x12\x1e\n" +
	"\n" +
	"unknownIds\x18\x04 \x03(\tR\n" +
	"unknownIds\x12\x1e\n" +
	"\n" +
	"orderedIds\x18\x05 \x03(\tR\n" +
	"orderedIds\x12@\n" +
	"\rlistResponses\x18\x06 \x03(\v2\x1a.pcov.proto.PBListResponseR\rlistResponses\"\x84\x03\n" +
	"\x0ePBListResponse\x12\x16\n" +
	"\x06listId\x18\x01 \x01(\tR\x06listId\x12\x1e\n" +
	"\n" +
	"isFullSync\x18\x02 \x01(\bR\n" +
	"isFullSync\x12*\n" +
	"\x10logicalTimestamp\x18\x03 \x01(\x04R\x10logicalTimestamp\x12_\n" +
	"\x16categoryGroupResponses\x18\a \x03(\v2'.pcov.proto.PBListCategoryGroupResponseR\x16categoryGroupResponses\x128\n" +
	"\x17deletedCategoryGroupIds\x18\b \x03(\tR\x17deletedCategoryGroupIds\x12=\n" +
	"\fstoreFilters\x18\v \x03(\v2\x19.pcov.proto.PBStoreFilterR\fstoreFilters\x124\n" +
	"\x15deletedStoreFilterIds\x18\f \x03(\tR\x15deletedStoreFilterIds\"y\n" +
	"\rPBStoreFilter\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x02(\tR\n" +
	"identifier\x12\x16\n" +
	"\x06listId\x18\x03 \x01(\tR\x06listId\x120\n" +
	"\x13listCategoryGroupId\x18\b \x01(\tR\x13listCategoryGroupId\"\x8c\x02\n" +
	"\x0ePBListCategory\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12*\n" +
	"\x10logicalTimestamp\x18\x02 \x01(\x04R\x10logicalTimestamp\x12(\n" +
	"\x0fcategoryGroupId\x18\x03 \x01(\tR\x0fcategoryGroupId\x12\x16\n" +
	"\x06listId\x18\x04 \x01(\tR\x06listId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x06 \x01(\tR\x04icon\x12&\n" +
	"\x0esystemCategory\x18\a \x01(\tR\x0esystemCategory\x12\x1c\n" +
	"\tsortIndex\x18\t \x01(\x05R\tsortIndex\"\x85\x03\n" +
	"\x13PBListCategoryGroup\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12*\n" +
	"\x10logicalTimestamp\x18\x02 \x01(\x04R\x10logicalTimestamp\x12\x16\n" +
	"\x06listId\x18\x03 \x01(\tR\x06listId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12:\n" +
	"\n" +
	"categories\x18\x05 \x03(\v2\x1a.pcov.proto.PBListCategoryR\n" +
	"categories\x12,\n" +
	"\x11defaultCategoryId\x18\b \x01(\tR\x11defaultCategoryId\x12>\n" +
	"\x1acategoriesLogicalTimestamp\x18\x06 \x01(\x04R\x1acategoriesLogicalTimestamp\x12L\n" +
	"!deletedCategoriesLogicalTimestamp\x18\a \x01(\x04R!deletedCategoriesLogicalTimestamp\"\x88\x01\n" +
	"\x1cPBListItemCategoryAssignment\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12(\n" +
	"\x0fcategoryGroupId\x18\x02 \x01(\tR\x0fcategoryGroupId\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x03 \x01(\tR\n" +
	"categoryId\"\xfa\x02\n" +
	"\x13PBOperationMetadata\x12 \n" +
	"\voperationId\x18\x01 \x01(\tR\voperationId\x12\x1c\n" +
	"\thandlerId\x18\x02 \x01(\tR\thandlerId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\x12&\n" +
	"\x0eoperationClass\x18\x04 \x01(\x05R\x0eoperationClass\x12*\n" +
	"\x10operationVersion\x18\x05 \x01(\x05R\x10operationVersion\"\xb6\x01\n" +
	"\x0eOperationClass\x12\x16\n" +
	"\x12UndefinedOperation\x10\x00\x12\x12\n" +
	"\x0eStoreOperation\x10\x01\x12\x18\n" +
	"\x14StoreFilterOperation\x10\x02\x12\x19\n" +
	"\x15ListCategoryOperation\x10\x03\x12\x1e\n" +
	"\x1aListCategoryGroupOperation\x10\x04\x12#\n" +
	"\x1fListCategorizationRuleOperation\x10\x05\"\xa9\x03\n" +
	"\x0fPBListOperation\x12;\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.pcov.proto.PBOperationMetadataR\bmetadata\x12\x16\n" +
	"\x06listId\x18\x02 \x01(\tR\x06listId\x12\x1e\n" +
	"\n" +
	"listItemId\x18\x03 \x01(\tR\n" +
	"listItemId\x12\"\n" +
	"\fupdatedValue\x18\x04 \x01(\tR\fupdatedValue\x12$\n" +
	"\roriginalValue\x18\x05 \x01(\tR\roriginalValue\x120\n" +
	"\blistItem\x18\x06 \x01(\v2\x14.pcov.proto.ListItemR\blistItem\x12,\n" +
	"\x04list\x18\a \x01(\v2\x18.pcov.proto.ShoppingListR\x04list\x12\"\n" +
	"\flistFolderId\x18\b \x01(\tR\flistFolderId\x12S\n" +
	"\x14updatedCategoryGroup\x18\x13 \x01(\v2\x1f.pcov.proto.PBListCategoryGroupR\x14updatedCategoryGroup\"R\n" +
	"\x13PBListOperationList\x12;\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x1b.pcov.proto.PBListOperationR\n" +
	"operations\"\xab\x02\n" +
	"\x1cPBShareListOperationResponse\x12=\n" +
	"\n" +
	"sharedUser\x18\x01 \x01(\v2\x1d.pcov.proto.PBEmailUserIDPairR\n" +
	"sharedUser\x124\n" +
	"\x15originalListTimestamp\x18\x02 \x01(\x01R\x15originalListTimestamp\x122\n" +
	"\x14updatedListTimestamp\x18\x03 \x01(\x01R\x14updatedListTimestamp\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x1e\n" +
	"\n" +
	"errorTitle\x18\x05 \x01(\tR\n" +
	"errorTitle\x12\"\n" +
	"\ferrorMessage\x18\x06 \x01(\tR\ferrorMessage\"\xec\x01\n" +
	"\x15PBListFolderOperation\x12;\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.pcov.proto.PBOperationMetadataR\bmetadata\x12\x1e\n" +
	"\n" +
	"listDataId\x18\x02 \x01(\tR\n" +
	"listDataId\x12>\n" +
	"\vfolderItems\x18\x04 \x03(\v2\x1c.pcov.proto.PBListFolderItemR\vfolderItems\x126\n" +
	"\x16originalParentFolderId\x18\x05 \x01(\tR\x16originalParentFolderId\"^\n" +
	"\x19PBListFolderOperationList\x12A\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2!.pcov.proto.PBListFolderOperationR\n" +
	"operations\"\xd6\x01\n" +
	"\x0ePBListSettings\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x02(\tR\n" +
	"identifier\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06listId\x18\x03 \x01(\tR\x06listId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x01R\ttimestamp\x12$\n" +
	"\rstoreFilterId\x18\x14 \x01(\tR\rstoreFilterId\x120\n" +
	"\x13listCategoryGroupId\x18\x1b \x01(\tR\x13listCategoryGroupId\"L\n" +
	"\x12PBListSettingsList\x126\n" +
	"\bsettings\x18\x02 \x03(\v2\x1a.pcov.proto.PBListSettingsR\bsettings\"\x9c\x01\n" +
	"\x17PBListSettingsOperation\x12;\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.pcov.proto.PBOperationMetadataR\bmetadata\x12D\n" +
	"\x0fupdatedSettings\x18\x02 \x01(\v2\x1a.pcov.proto.PBListSettingsR\x0fupdatedSettings\"b\n" +
	"\x1bPBListSettingsOperationList\x12C\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2#.pcov.proto.PBListSettingsOperationR\n" +
	"operations\"K\n" +
	"\x17PBEditOperationResponse\x120\n" +
	"\x13processedOperations\x18\x03 \x03(\tR\x13processedOperations\"]\n" +
	"\x11PBEmailUserIDPair\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bfullName\x18\x03 \x01(\tR\bfullName\"\x96\x02\n" +
	"\x12PBUserDataResponse\x12W\n" +
	"\x15shoppingListsResponse\x18\x01 \x01(\v2!.pcov.proto.ShoppingListsResponseR\x15shoppingListsResponse\x12S\n" +
	"\x13listFoldersResponse\x18\x02 \x01(\v2!.pcov.proto.PBListFoldersResponseR\x13listFoldersResponse\x12R\n" +
	"\x14listSettingsResponse\x18\t \x01(\v2\x1e.pcov.proto.PBListSettingsListR\x14listSettingsResponseB,Z*github.com/cosgroveb/al/internal/anylistpb"

var (
	file_internal_anylistpb_anylist_proto_rawDescOnce sync.Once
	file_internal_anylistpb_anylist_proto_rawDescData []byte
)

func file_internal_anylistpb_anylist_proto_rawDescGZIP() []byte {
	file_internal_anylistpb_anylist_proto_rawDescOnce.Do(func() {
		file_internal_anylistpb_anylist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_anylistpb_anylist_proto_rawDesc), len(file_internal_anylistpb_anylist_proto_rawDesc)))
	})
	return file_internal_anylistpb_anylist_proto_rawDescData
}

var file_internal_anylistpb_anylist_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_internal_anylistpb_anylist_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_internal_anylistpb_anylist_proto_goTypes = []any{
	(ShoppingList_ListItemSortOrder)(0),     // 0: pcov.proto.ShoppingList.ListItemSortOrder
	(ShoppingList_NewListItemPosition)(0),   // 1: pcov.proto.ShoppingList.NewListItemPosition
	(PBListFolderItem_ItemType)(0),          // 2: pcov.proto.PBListFolderItem.ItemType
	(PBOperationMetadata_OperationClass)(0), // 3: pcov.proto.PBOperationMetadata.OperationClass
	(*ShoppingList)(nil),                    // 4: pcov.proto.ShoppingList
	(*PBItemQuantity)(nil),                  // 5: pcov.proto.PBItemQuantity
	(*ListItem)(nil),                        // 6: pcov.proto.ListItem
	(*PBListFolderItem)(nil),                // 7: pcov.proto.PBListFolderItem
	(*PBListFolder)(nil),                    // 8: pcov.proto.PBListFolder
	(*PBListFoldersResponse)(nil),           // 9: pcov.proto.PBListFoldersResponse
	(*PBListCategoryGroupResponse)(nil),     // 10: pcov.proto.PBListCategoryGroupResponse
	(*ShoppingListsResponse)(nil),           // 11: pcov.proto.ShoppingListsResponse
	(*PBListResponse)(nil),                  // 12: pcov.proto.PBListResponse
	(*PBStoreFilter)(nil),                   // 13: pcov.proto.PBStoreFilter
	(*PBListCategory)(nil),                  // 14: pcov.proto.PBListCategory
	(*PBListCategoryGroup)(nil),             // 15: pcov.proto.PBListCategoryGroup
	(*PBListItemCategoryAssignment)(nil),    // 16: pcov.proto.PBListItemCategoryAssignment
	(*PBOperationMetadata)(nil),             // 17: pcov.proto.PBOperationMetadata
	(*PBListOperation)(nil),                 // 18: pcov.proto.PBListOperation
	(*PBListOperationList)(nil),             // 19: pcov.proto.PBListOperationList
	(*PBShareListOperationResponse)(nil),    // 20: pcov.proto.PBShareListOperationResponse
	(*PBListFolderOperation)(nil),           // 21: pcov.proto.PBListFolderOperation
	(*PBListFolderOperationList)(nil),       // 22: pcov.proto.PBListFolderOperationList
	(*PBListSettings)(nil),                  // 23: pcov.proto.PBListSettings
	(*PBListSettingsList)(nil),              // 24: pcov.proto.PBListSettingsList
	(*PBListSettingsOperation)(nil),         // 25: pcov.proto.PBListSettingsOperation
	(*PBListSettingsOperationList)(nil),     // 26: pcov.proto.PBListSettingsOperationList
	(*PBEditOperationResponse)(nil),         // 27: pcov.proto.PBEditOperationResponse
	(*PBEmailUserIDPair)(nil),               // 28: pcov.proto.PBEmailUserIDPair
	(*PBUserDataResponse)(nil),              // 29: pcov.proto.PBUserDataResponse
}
var file_internal_anylistpb_anylist_proto_depIdxs = []int32{
	6,  // 0: pcov.proto.ShoppingList.items:type_name -> pcov.proto.ListItem
	28, // 1: pcov.proto.ShoppingList.sharedUsers:type_name -> pcov.proto.PBEmailUserIDPair
	16, // 2: pcov.proto.ListItem.categoryAssignments:type_name -> pcov.proto.PBListItemCategoryAssignment
	5,  // 3: pcov.proto.ListItem.quantityPb:type_name -> pcov.proto.PBItemQuantity
	7,  // 4: pcov.proto.PBListFolder.items:type_name -> pcov.proto.PBListFolderItem
	8,  // 5: pcov.proto.PBListFoldersResponse.listFolders:type_name -> pcov.proto.PBListFolder
	15, // 6: pcov.proto.PBListCategoryGroupResponse.categoryGroup:type_name -> pcov.proto.PBListCategoryGroup
	4,  // 7: pcov.proto.ShoppingListsResponse.newLists:type_name -> pcov.proto.ShoppingList
	4,  // 8: pcov.proto.ShoppingListsResponse.modifiedLists:type_name -> pcov.proto.ShoppingList
	12, // 9: pcov.proto.ShoppingListsResponse.listResponses:type_name -> pcov.proto.PBListResponse
	10, // 10: pcov.proto.PBListResponse.categoryGroupResponses:type_name -> pcov.proto.PBListCategoryGroupResponse
	13, // 11: pcov.proto.PBListResponse.storeFilters:type_name -> pcov.proto.PBStoreFilter
	14, // 12: pcov.proto.PBListCategoryGroup.categories:type_name -> pcov.proto.PBListCategory
	17, // 13: pcov.proto.PBListOperation.metadata:type_name -> pcov.proto.PBOperationMetadata
	6,  // 14: pcov.proto.PBListOperation.listItem:type_name -> pcov.proto.ListItem
	4,  // 15: pcov.proto.PBListOperation.list:type_name -> pcov.proto.ShoppingList
	15, // 16: pcov.proto.PBListOperation.updatedCategoryGroup:type_name -> pcov.proto.PBListCategoryGroup
	18, // 17: pcov.proto.PBListOperationList.operations:type_name -> pcov.proto.PBListOperation
	28, // 18: pcov.proto.PBShareListOperationResponse.sharedUser:type_name -> pcov.proto.PBEmailUserIDPair
	17, // 19: pcov.proto.PBListFolderOperation.metadata:type_name -> pcov.proto.PBOperationMetadata
	7,  // 20: pcov.proto.PBListFolderOperation.folderItems:type_name -> pcov.proto.PBListFolderItem
	21, // 21: pcov.proto.PBListFolderOperationList.operations:type_name -> pcov.proto.PBListFolderOperation
	23, // 22: pcov.proto.PBListSettingsList.settings:type_name -> pcov.proto.PBListSettings
	17, // 23: pcov.proto.PBListSettingsOperation.metadata:type_name -> pcov.proto.PBOperationMetadata
	23, // 24: pcov.proto.PBListSettingsOperation.updatedSettings:type_name -> pcov.proto.PBListSettings
	25, // 25: pcov.proto.PBListSettingsOperationList.operations:type_name -> pcov.proto.PBListSettingsOperation
	11, // 26: pcov.proto.PBUserDataResponse.shoppingListsResponse:type_name -> pcov.proto.ShoppingListsResponse
	9,  // 27: pcov.proto.PBUserDataResponse.listFoldersResponse:type_name -> pcov.proto.PBListFoldersResponse
	24, // 28: pcov.proto.PBUserDataResponse.listSettingsResponse:type_name -> pcov.proto.PBListSettingsList
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_internal_anylistpb_anylist_proto_init() }
func file_internal_anylistpb_anylist_proto_init() {
	if File_internal_anylistpb_anylist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_anylistpb_anylist_proto_rawDesc), len(file_internal_anylistpb_anylist_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_anylistpb_anylist_proto_goTypes,
		DependencyIndexes: file_internal_anylistpb_anylist_proto_depIdxs,
		EnumInfos:         file_internal_anylistpb_anylist_proto_enumTypes,
		MessageInfos:      file_internal_anylistpb_anylist_proto_msgTypes,
	}.Build()
	File_internal_anylistpb_anylist_proto = out.File
	file_internal_anylistpb_anylist_proto_goTypes = nil
	file_internal_anylistpb_anylist_proto_depIdxs = nil
}
